### PR TITLE
Ruleapplier and fixing rules to use Notes instead of Ints

### LINKED ISSUE #10: Rule Applier class
Class that takes in possible notes and other input from the generator and applies all static (E.G. non-weighted) rules in the rule set. Mutates the input possibilities object.

Current inputs needed:
```
RuleInput object with:
    List<int> Possibilities
    int CurrentNote
    int Position
    int Length
    int PreviousCantus
    int PreviousCounterpoint
```

### PR DESCRIPTION
**Pull request by Dylan-Riley**
~~Currently (22/JUL) exists to show code, not ready for merge or full review yet.~~

Resolves https://github.com/theanticrumpet/CounterpointGenerator/issues/10

Adds RuleApplier class for non-weighted rules, builds ruleset using `GenerateRuleset()` method and then `Applicator()` method can be called with a ruleInput parameter to step through each rule and trim down the possibilities list.

-----

Changes to Generator:
> Implement GenerateNoteAtRegion to return a List<Note> of every note from (n.Pitch -13) to (n.Pitch +13)
> Redone CounterpointForNote to take in all input required for a full ruleInput and use the RuleApplier.GenerateSet() and RuleApplier.Applicator(RuleInput ri) methods
> Adjusted parameters of GenerateCounterpointForNoteStack

Changes to Note:
> Added constructors for default length and to provide length
> Added Note.Equals(Note n) method

Changes to MelodyLine:
> Added MelodyLine.Length() method

Changes to RuleInput:
> Added constructor

Changes to Rules:
> Now use Note objects with Note.Pitch instead of just raw ints
> Battuta specific: Added position == 0 case, Fixed note removal logic to work with objects instead of the much easier raw int

### CODE REVIEW

**Comment by Dylan-Riley** [comment]
Also slight fix to logic in BattutaRule in 8cf285a

**Comment by Dylan-Riley** [comment]
~~27/JUL wait for review on fixing with https://github.com/theanticrumpet/CounterpointGenerator/pull/8 merge~~

Update types from `List<int>` to `MelodyLine` and `int` to `Note` where relevant

**Comment by Dylan-Riley** [comment]
9a65fa2 
As in fetch, checkout main, pull, checkout feature, merge master (into feature)

File: CounterpointGenerator/CounterpointGenerator/Generator.cs [hunk 1]
```diff
@@ -40,21 +40,36 @@ private List<MelodyLine> GenerateCounterpointForNoteStack(MelodyLine m, Note? pr
...
 
         private List<Note> GenerateNoteAtRegion(Note n)
         {
-            throw new NotImplementedException();
+            int upperPitch = n.Pitch + 13; // +1 octave
+            int lowerPitch = n.Pitch - 13; // -1 octave
+            List<Note> output = new List<Note>();
+            for (int addPitch = lowerPitch; addPitch <= upperPitch; addPitch++)
+            {
+                // TODO: Fix for note length when that becomes something to worry about
```
Comment (aditink) [inline CounterpointGenerator/CounterpointGenerator/Generator.cs:69]: List<note> output = Enumerable.Range(n.Pitch - 13, n.Pitch + 13).Select(pitch=>new Note(pitch)).ToList();

File: CounterpointGenerator/CounterpointGenerator/Generator.cs [hunk 2]
```diff
@@ -40,21 +40,36 @@ private List<MelodyLine> GenerateCounterpointForNoteStack(MelodyLine m, Note? pr
...
+                throw new Exception("Ruleset did not generate properly!");
+            }
+
+            return ruleInput.Possibilities;
         }
 
         private List<Note> GenerateNoteAtRegion(Note n)
         {
-            throw new NotImplementedException();
+            int upperPitch = n.Pitch + 13; // +1 octave
```
Comment (aditink) [inline CounterpointGenerator/CounterpointGenerator/Generator.cs]: Avoid "magic numbers".
https://www.c-sharpcorner.com/UploadFile/b7dc95/writing-clean-code-and-magic-numbers/

File: CounterpointGenerator/CounterpointGenerator/Generator.cs (hunk 1 above)
Comment (Dylan-Riley) [reply CounterpointGenerator/CounterpointGenerator/Generator.cs:69]: Oh, that's convenient

Comment (Dylan-Riley) [reply CounterpointGenerator/CounterpointGenerator/Generator.cs:69]: It would actually need to be 
```csharp
List<Note> test = Enumerable.Range(-13, 27).Select(pitch => new Note(pitch)).ToList()
```
To get the full 13 semitones on either side of the pitch since it's 
```csharp
Enumerable.Range(int start, int count)
```
"Count" not "End"
So the logic would have to be something like (n.Pitch - 13, n,Pitch + (13*2 + 1)) which while the Enumerable trick is cool I honestly think makes it look so much messier it outweighs the benefits of it.

File: CounterpointGenerator/CounterpointGenerator/Rules/BattutaRule.cs [hunk 3]
```diff
@@ -13,27 +13,37 @@ class BattutaRule : IRules
...
-            if (ruleInput.PreviousCantus < ruleInput.CurrentNote)
+            if (ruleInput.PreviousCantus.Pitch < ruleInput.CurrentNote.Pitch)
             {
                 // Check if previous counterpoint was the higher voice
-                if(ruleInput.PreviousCounterpoint > ruleInput.PreviousCantus)
+                if(ruleInput.PreviousCounterpoint.Pitch > ruleInput.PreviousCantus.Pitch)
                 {
                     // Remove upper octave as a possibility
-                    output.Remove(ruleInput.CurrentNote + 13);
+                    Note removeNote = new Note(ruleInput.CurrentNote.Pitch + 13, ruleInput.CurrentNote.Length);
```
Comment (aditink) [inline CounterpointGenerator/CounterpointGenerator/Rules/BattutaRule.cs]: It looks like you meant to remove an octave of possibilities, not just the note an octave above this note. Perhaps you want output.RemoveAll(n => n.Pitch > ruleInput.CurrentNote.Pitch);

File: CounterpointGenerator/CounterpointGenerator/Rules/BattutaRule.cs [hunk 4]
```diff
@@ -13,27 +13,37 @@ class BattutaRule : IRules
...
+                    output.RemoveAll(n => n.Pitch == removeNote.Pitch);
                 }
             }
             // Check if previous cantus stepped down
-            else if (ruleInput.PreviousCantus > ruleInput.CurrentNote)
+            else if (ruleInput.PreviousCantus.Pitch > ruleInput.CurrentNote.Pitch)
             {
                 // Check if previous counterpoint was the lower voice
-                if(ruleInput.PreviousCounterpoint < ruleInput.PreviousCantus)
+                if(ruleInput.PreviousCounterpoint.Pitch < ruleInput.PreviousCantus.Pitch)
```
Comment (aditink) [inline CounterpointGenerator/CounterpointGenerator/Rules/BattutaRule.cs]: You can collapse these conditionals by using an &

File: CounterpointGenerator/CounterpointGenerator/Rules/RuleApplier.cs [hunk 5]
```diff
@@ -0,0 +1,43 @@
...
+
+        public Boolean GenerateSet()
+        {
+            // Build ruleset
+            // Non-weighted rules, weighted chance rules to be handled elsewhere
+            ruleSet.Add(new StartEndPerfectRule());
+            ruleSet.Add(new PenultimateNoteRule());
+            ruleSet.Add(new BattutaRule());
+
+            // Return true if all rules added
```
Comment (aditink) [inline CounterpointGenerator/CounterpointGenerator/Rules/RuleApplier.cs:23]: return ruleSet.Count == 3

File: CounterpointGenerator/CounterpointGenerator/Generator.cs [hunk 6]
```diff
@@ -40,21 +40,36 @@ private List<MelodyLine> GenerateCounterpointForNoteStack(MelodyLine m, Note? pr
...
         }
 
-        private List<Note> CounterpointForNote(Note n, Note prevN, Note preCtp)
+        private List<Note> CounterpointForNote(Note n, Note prevN, Note preCtp, int melodyLength, int generateCount)
         {
             List<Note> possibleNotes = GenerateNoteAtRegion(n);
-            List<Note> possibleNotesAfterRules = new List<Note>();
-            /*foreach(IRules r in Dictionary[input.userPreference])
+            // Possibilities, currentNote, position, length, previousCantus, previousCounterpoint
+            RuleInput ruleInput = new RuleInput(possibleNotes, n, generateCount, melodyLength, prevN, preCtp);
```
Comment (aditink) [inline CounterpointGenerator/CounterpointGenerator/Generator.cs:47]: Why do we want to create a new ruleInput object every time?

File: CounterpointGenerator/CounterpointGenerator/Rules/imperfectConsonanceRule.cs [hunk 7]
```diff
@@ -19,11 +19,11 @@ public class ImperfectConsonanceRule: IRules {
...
          */
-        public List<int> Apply(RuleInput ruleInput){
-            List<int> output = new List<int>();
-            foreach (int n in ruleInput.Possibilities) {
+        public List<Note> Apply(RuleInput ruleInput){
+            List<Note> output = new List<Note>();
+            foreach (Note n in ruleInput.Possibilities) {
                 // Add checking outside one octave range?
-                if (imperfectIntervals.Contains(n - ruleInput.CurrentNote)){
+                if (imperfectIntervals.Contains(n.Pitch - ruleInput.CurrentNote.Pitch)){
```
Comment (aditink) [inline CounterpointGenerator/CounterpointGenerator/Rules/imperfectConsonanceRule.cs:26]: For this to work outside an octave range, you can just add a %13

File: CounterpointGenerator/CounterpointGenerator/Generator.cs (hunk 2 above)
Comment (aditink) [reply CounterpointGenerator/CounterpointGenerator/Generator.cs]: Since 13 (octave) is project-wide consider doing something like in the top answer here. https://stackoverflow.com/questions/2032978/how-to-manage-project-wide-constants-in-a-project-using-c

**Review by aditink — CHANGES_REQUESTED** [review]

File: CounterpointGenerator/CounterpointGenerator/Rules/imperfectConsonanceRule.cs (hunk 7 above)
Comment (aditink) [reply CounterpointGenerator/CounterpointGenerator/Rules/imperfectConsonanceRule.cs:26]: (Just an observation, you don't have to do this right now)

File: CounterpointGenerator/CounterpointGenerator/Generator.cs (hunk 1 above)
Comment (aditink) [reply CounterpointGenerator/CounterpointGenerator/Generator.cs:69]: Oh, nice catch!
This comes down to personal preference but I think once you have constants in place (from one of the other comments) Range(n.pitch-octave, generationRange) is tame enough

File: CounterpointGenerator/CounterpointGenerator/Rules/BattutaRule.cs (hunk 3 above)
Comment (Dylan-Riley) [reply CounterpointGenerator/CounterpointGenerator/Rules/BattutaRule.cs]: No, I meant to specifically remove only the octave here. If the higher voice steps down and the lower voice steps up they cannot be an octave apart. You can see the original version before the change had only to remove the int value equal to an octave, the first thing I typed had Remove(new Note(/*octave*/)) which I later realized wouldn't work because even though the values are the same the object is different

File: CounterpointGenerator/CounterpointGenerator/Generator.cs (hunk 6 above)
Comment (Dylan-Riley) [reply CounterpointGenerator/CounterpointGenerator/Generator.cs:47]: Every field in the RuleInput is different every time CounterpointForNote is called. It gets called once, then the ruleapplier handles every rule sequentially, then CounterpointForNote returns the final list. The next recursion of GenerateCounterpointForNoteStack will have all new values for almost every field RuleInput wants

File: CounterpointGenerator/CounterpointGenerator/Rules/RuleApplier.cs (hunk 5 above)
Comment (Dylan-Riley) [reply CounterpointGenerator/CounterpointGenerator/Rules/RuleApplier.cs:23]: Resolved 4088c42

File: CounterpointGenerator/CounterpointGenerator/Rules/BattutaRule.cs (hunk 4 above)
Comment (Dylan-Riley) [reply CounterpointGenerator/CounterpointGenerator/Rules/BattutaRule.cs]: Resolved 59bf229

File: CounterpointGenerator/CounterpointGenerator/Generator.cs (hunk 1 above)
Comment (Dylan-Riley) [reply CounterpointGenerator/CounterpointGenerator/Generator.cs:69]: I, personally, strongly prefer the for loop. It's just super easy to look at and see exactly what it does

File: CounterpointGenerator/CounterpointGenerator/Generator.cs (hunk 2 above)
Comment (Dylan-Riley) [reply CounterpointGenerator/CounterpointGenerator/Generator.cs]: Resolved a9a7fdc

File: CounterpointGenerator/CounterpointGenerator/Generator.cs (hunk 6 above)
Comment (aditink) [reply CounterpointGenerator/CounterpointGenerator/Generator.cs:47]: Oh, sorry, I meant RuleApplier (next line)

File: CounterpointGenerator/CounterpointGenerator/Rules/BattutaRule.cs [hunk 8]
```diff
@@ -13,28 +13,34 @@ class BattutaRule : IRules
...
+                ruleInput.PreviousCounterpoint.Pitch > ruleInput.PreviousCantus.Pitch)
             {
-                // Check if previous counterpoint was the higher voice
-                if(ruleInput.PreviousCounterpoint > ruleInput.PreviousCantus)
-                {
-                    // Remove upper octave as a possibility
-                    output.Remove(ruleInput.CurrentNote + 13);
-                }
+                // Remove upper octave as a possibility
+                Note removeNote = new Note(ruleInput.CurrentNote.Pitch + 13, ruleInput.CurrentNote.Length);
```
Comment (aditink) [inline CounterpointGenerator/CounterpointGenerator/Rules/BattutaRule.cs]: 13 -> Octave. Also, it seems like you only need ruleInput.CurrentNote.Pitch + 13, consider making  an int instead of incurring the Note object creation/destruction overhead.

**Review by aditink — CHANGES_REQUESTED** [review]

File: CounterpointGenerator/CounterpointGenerator/Rules/BattutaRule.cs (hunk 8 above)
Comment (Dylan-Riley) [reply CounterpointGenerator/CounterpointGenerator/Rules/BattutaRule.cs]: Resolved ca34865

**Review by aditink — APPROVED** [review]

**Comment by Dylan-Riley** [comment]
Future updates: 

Rules need to be singleton instead of declared. Option 1: Declare them in Program.cs in that .AddSingleton< ... > block. Option 2: Implement a singleton myself. For now, don't bother with this.

RuleApplier will also need to be created with dependency injection. Gonna have to register RuleApplier in program.cs, instead of a singleton it's gonna want to be a "transient(?)" (something on per request)
